# Generated by Django 4.2.3 on 2023-07-13 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import edu_stracture.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu', '0004_alter_instcourse_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='eduDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, upload_to=edu_stracture.models.upload_path)),
                ('dateOfcreation', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
            ],
        ),
        migrations.CreateModel(
            name='eduSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, upload_to=edu_stracture.models.upload_path)),
                ('dateOfcreation', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
            ],
        ),
        migrations.CreateModel(
            name='eduRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('dateOfcreation', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
            ],
        ),
        migrations.CreateModel(
            name='eduLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('dateOfcreation', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_stracture.edudepartment')),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
            ],
        ),
        migrations.CreateModel(
            name='eduClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, upload_to=edu_stracture.models.upload_path)),
                ('dateOfcreation', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.instcourse')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_stracture.edudepartment')),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
                ('semister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.semester')),
            ],
        ),
    ]
