# Generated by Django 4.0.5 on 2023-07-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_post', '0002_blogpost_featured_image_blogpost_meta_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='user',
            new_name='author',
        ),
    ]
