# Generated by Django 4.2.3 on 2023-07-14 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import edu_members.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu_recruiter', '0001_initial'),
        ('edu', '0004_alter_instcourse_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentAdmitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfGardiner', models.CharField(blank=True, max_length=70)),
                ('contactOfGardiner', models.CharField(blank=True, max_length=70)),
                ('postalCode', models.CharField(blank=True, max_length=70)),
                ('address1', models.TextField(blank=True)),
                ('address2', models.TextField(blank=True)),
                ('religion', models.CharField(blank=True, max_length=120)),
                ('demicile', models.CharField(blank=True, max_length=100)),
                ('provence', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('Districe', models.CharField(blank=True, max_length=120)),
                ('Tehsil', models.CharField(blank=True, max_length=120)),
                ('hafaza_Quran', models.BooleanField(default=False)),
                ('educlass', models.CharField(max_length=70)),
                ('lastResult', models.CharField(max_length=300)),
                ('gradeLvl', models.CharField(max_length=70)),
                ('anyHonorsAwards', models.TextField(blank=True)),
                ('dateOfapplyed', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('student', models.BooleanField(default=True)),
                ('cv', models.FileField(blank=True, upload_to=edu_members.models.upload_path)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_recruiter.admissionfrom')),
                ('userS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobCvForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalCode', models.CharField(blank=True, max_length=70)),
                ('address1', models.TextField(blank=True)),
                ('address2', models.TextField(blank=True)),
                ('religion', models.CharField(blank=True, max_length=120)),
                ('demicile', models.CharField(blank=True, max_length=100)),
                ('provence', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('Districe', models.CharField(blank=True, max_length=120)),
                ('Tehsil', models.CharField(blank=True, max_length=120)),
                ('anyHonorsAwards', models.TextField(blank=True)),
                ('dateOfapplyed', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cv', models.FileField(blank=True, upload_to=edu_members.models.upload_path)),
                ('is_staff', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_recruiter.jobrecruitry')),
                ('userS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='eduStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('eduID', models.CharField(blank=True, max_length=50, null=True)),
                ('joinedAt', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('disable', models.BooleanField(default=False)),
                ('ex_Student', models.BooleanField(default=False)),
                ('dataForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_members.studentadmitform')),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EduMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduID', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('dateOfReg', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
                ('eduStudent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_members.studentadmitform')),
                ('eduemployees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_members.jobcvform')),
                ('group', models.ManyToManyField(to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='eduFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('eduID', models.CharField(blank=True, max_length=50, null=True)),
                ('joinedAt', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('disable', models.BooleanField(default=False)),
                ('ex_Faculty', models.BooleanField(default=False)),
                ('dataForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_members.jobcvform')),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
