# Generated by Django 4.2.3 on 2023-07-15 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu_members', '0003_alter_edufaculty_user_alter_edustudents_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edufaculty',
            name='equiet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edufaculty',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edustudents',
            name='equiet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edustudents',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='edufaculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='edustudents',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobcvform',
            name='userS',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentadmitform',
            name='userS',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
