# Generated by Django 4.0.5 on 2023-07-26 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu_members', '0004_edufaculty_equiet_edufaculty_suspend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edufaculty',
            name='dataForm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_members.jobcvform'),
        ),
        migrations.AlterField(
            model_name='edufaculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iam_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='edustudents',
            name='dataForm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_members.studentadmitform'),
        ),
        migrations.AlterField(
            model_name='edustudents',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iam_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EduMember',
        ),
    ]
