# Generated by Django 4.2.3 on 2023-07-14 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import edu_recruiter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu', '0004_alter_instcourse_id'),
        ('edu_stracture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobRecruitry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('joining', models.DateField()),
                ('lastDate', models.DateField()),
                ('seats', models.IntegerField()),
                ('dateOfcreation', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('disable', models.BooleanField(default=False)),
                ('ad', models.ImageField(blank=True, null=True, upload_to=edu_recruiter.models.upload_path)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Expired', 'Expired')], default='Ongoing', max_length=20)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
                ('forPost', models.ManyToManyField(blank=True, to='edu_stracture.edurole')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('sectionStart', models.DateField()),
                ('sectionEnd', models.DateField()),
                ('lastDate', models.DateField()),
                ('seats', models.IntegerField()),
                ('bachno', models.IntegerField()),
                ('dateOfcreation', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('disable', models.BooleanField(default=False)),
                ('ad', models.ImageField(blank=True, null=True, upload_to=edu_recruiter.models.upload_path)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Expired', 'Expired')], default='Ongoing', max_length=20)),
                ('course', models.ManyToManyField(blank=True, to='edu.instcourse')),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
            ],
        ),
    ]
