# Generated by Django 4.2.3 on 2023-07-17 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_onLine_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electure',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_onLine_class.eclassvideos'),
        ),
    ]
