# Generated by Django 4.2.3 on 2023-07-17 07:40

from django.db import migrations, models
import edu_onLine_class.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_onLine_class', '0002_alter_electure_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eclassvideos',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='eclassvideos',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=edu_onLine_class.models.upload_thumbnail),
        ),
        migrations.AlterField(
            model_name='eclassvideos',
            name='video',
            field=models.FileField(null=True, upload_to=edu_onLine_class.models.upload_path),
        ),
    ]
