# Generated by Django 4.2.3 on 2023-07-17 08:27

from django.db import migrations, models
import edu_onLine_class.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_onLine_class', '0004_alter_eclassvideos_name_alter_electure_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eclassvideos',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=edu_onLine_class.models.upload_thumbnail),
        ),
        migrations.AlterField(
            model_name='eclassvideos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=edu_onLine_class.models.upload_path),
        ),
    ]
