# Generated by Django 4.2.3 on 2023-07-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_onLine_class', '0005_alter_eclassvideos_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='electure',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_onLine_class.eclassvideos'),
        ),
    ]
