# Generated by Django 4.0.5 on 2023-07-19 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edu_onLine_class', '0007_alter_attendance_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='electureNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('notes', models.FileField(blank=True, null=True, upload_to=None)),
                ('dateOfUplaoding', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electure_notes', to='edu_onLine_class.electure')),
            ],
        ),
    ]
