# Generated by Django 4.0.5 on 2023-07-19 10:54

from django.db import migrations, models
import edu_onLine_class.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_onLine_class', '0008_electurenotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electurenotes',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to=edu_onLine_class.models.upload_notes),
        ),
    ]
