# Generated by Django 4.0.5 on 2023-08-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_edustorage'),
        ('edu_stracture', '0001_initial'),
        ('edu_onLine_class', '0010_alter_classofstudents_eclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='eclassvideos',
            name='Eclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Video_for_leacture_Eclass', to='edu_stracture.educlass'),
        ),
        migrations.AddField(
            model_name='eclassvideos',
            name='edu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electure_video_EDU', to='edu.xeduinstitution'),
        ),
    ]
