# Generated by Django 4.2.3 on 2023-07-12 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import edu.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('publication', models.CharField(max_length=150)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=75)),
                ('descripition', models.TextField()),
                ('totalfee', models.CharField(max_length=75)),
                ('totalSimsters', models.IntegerField(blank=True, null=True)),
                ('smFull', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='xEduInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to=edu.models.upload_path)),
                ('registration_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('pk_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('OwnerOfX', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('typeOfInstitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.institutiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('fee', models.CharField(max_length=75)),
                ('books', models.ManyToManyField(blank=True, to='edu.book')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.instcourse')),
            ],
        ),
        migrations.CreateModel(
            name='InstMediaUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
            ],
        ),
        migrations.AddField(
            model_name='instcourse',
            name='edu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution'),
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ManyToManyField(blank=True, to='edu.instcourse'),
        ),
    ]
