# Generated by Django 4.2.3 on 2023-07-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_alter_book_author_alter_book_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeduinstitution',
            name='pk_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
