# Generated by Django 4.0.5 on 2023-07-26 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu', '0004_alter_instcourse_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='userEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True)),
                ('since_in', models.DateTimeField(auto_now_add=True)),
                ('till_out', models.DateTimeField()),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.xeduinstitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam_in_edu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
