# Generated by Django 4.0.5 on 2023-07-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_useredu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useredu',
            name='till_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
