# Generated by Django 4.0.5 on 2023-08-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_useredu_study_at_useredu_work_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='eduStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalStorage', models.IntegerField(verbose_name=0)),
                ('allowStorage', models.IntegerField(verbose_name=10)),
                ('is_full', models.BooleanField(verbose_name=False)),
                ('LastMeasure', models.DateTimeField(auto_now_add=True)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_storage', to='edu.xeduinstitution')),
            ],
        ),
    ]
