# Generated by Django 4.0.5 on 2023-07-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu_members', '0004_edufaculty_equiet_edufaculty_suspend_and_more'),
        ('edu_onLine_class', '0009_alter_electurenotes_notes'),
        ('edu', '0004_alter_instcourse_id'),
        ('edu_stracture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Teacher Groups', max_length=50, null=True)),
                ('capacity', models.IntegerField(default=1)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_full', models.BooleanField(default=False)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_of_teachers', to='edu.xeduinstitution')),
                ('members', models.ManyToManyField(blank=True, related_name='teacher_of_edu', to='edu_members.edufaculty')),
            ],
        ),
        migrations.CreateModel(
            name='InchargeOfClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Class Incharge', max_length=50, null=True)),
                ('capacity', models.IntegerField(default=1)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_full', models.BooleanField(default=False)),
                ('Eclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InchargeOfEclass', to='edu_onLine_class.classofstudents')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_stracture.edudepartment')),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InchargeOfClassGroup', to='edu.xeduinstitution')),
                ('members', models.ManyToManyField(blank=True, related_name='incharge_of_class', to='edu_permissions.groupofteachers')),
            ],
        ),
        migrations.CreateModel(
            name='HeadOfTheDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Head Of the Department', max_length=50, null=True)),
                ('capacity', models.IntegerField(default=1)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_full', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_stracture.edudepartment')),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroupOfHeadOfDeparment', to='edu.xeduinstitution')),
                ('members', models.ManyToManyField(blank=True, related_name='head_of_the_department', to='edu_members.edufaculty')),
            ],
        ),
        migrations.CreateModel(
            name='HeadOfInstetude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Head Of Instetude', max_length=50, null=True)),
                ('capacity', models.IntegerField(default=1)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_full', models.BooleanField(default=False)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HeadOfInstetude', to='edu.xeduinstitution')),
                ('members', models.ManyToManyField(blank=True, related_name='head_of_instetude', to='edu_permissions.groupofteachers')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfSubHeadOfInstetude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Sub-head Of Instetude', max_length=50, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_full', models.BooleanField(default=False)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroupOfSubHeadOfInstetude', to='edu.xeduinstitution')),
                ('members', models.ManyToManyField(blank=True, related_name='sub_head_of_instetude', to='edu_permissions.groupofteachers')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Student Group', max_length=50, null=True)),
                ('capacity', models.IntegerField(default=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_full', models.BooleanField(default=False)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_of_students', to='edu.xeduinstitution')),
                ('members', models.ManyToManyField(blank=True, related_name='student_of_edu', to='edu_members.edustudents')),
            ],
        ),
    ]
