# Generated by Django 4.0.5 on 2023-07-21 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_alter_instcourse_id'),
        ('edu_members', '0004_edufaculty_equiet_edufaculty_suspend_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofsubheadofinstetude',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='sub_head_of_instetude', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='headofinstetude',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='head_of_instetude', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupOfAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Admin Group', max_length=50, null=True)),
                ('capacity', models.IntegerField(default=1)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_full', models.BooleanField(default=False)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_of_admins', to='edu.xeduinstitution')),
                ('members', models.ManyToManyField(blank=True, related_name='admin_of_edu', to='edu_members.edufaculty')),
            ],
        ),
    ]
