# Generated by Django 4.0.5 on 2023-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_permissions', '0002_alter_groupofsubheadofinstetude_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofstudents',
            name='capacity',
            field=models.IntegerField(default=120),
        ),
    ]
