# Generated by Django 4.0.5 on 2023-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_members', '0005_alter_edufaculty_dataform_alter_edufaculty_user_and_more'),
        ('edu_permissions', '0003_alter_groupofstudents_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inchargeofclass',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='incharge_of_class', to='edu_members.edufaculty'),
        ),
    ]
