# Generated by Django 4.0.5 on 2023-08-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_members', '0005_alter_edufaculty_dataform_alter_edufaculty_user_and_more'),
        ('edu_permissions', '0004_alter_inchargeofclass_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofsubheadofinstetude',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='sub_head_of_instetude', to='edu_members.edufaculty'),
        ),
        migrations.AlterField(
            model_name='headofinstetude',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='head_of_instetude', to='edu_members.edufaculty'),
        ),
    ]
