# Generated by Django 4.2.3 on 2023-07-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genuser',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
