# Generated by Django 4.2.3 on 2023-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_user', '0002_genuser_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genuser',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
